import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProvider from "./component/util_component/AppProvider";
import ListenerForAuth from "./component/util_component/ListenerForAuth";
import { Toast } from "./component/ui/Toast";
import Analyzer from "./component/ui/analyze/Analyzer";
import Connection from "./component/util_component/Connection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Toast />
          <ListenerForAuth />
          <Connection />
          <Analyzer />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
