import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "./component/util_component/AppProvider";
import ListenerForAuth from "./component/util_component/ListenerForAuth";
import { Toast } from "./component/ui/Toast";
import Analyzer from "./component/ui/analyze/Analyzer";
import Connection from "./component/util_component/Connection";
import { geistMono, inter } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className ?? geistMono.variable} antialiased`}>
        <AppProvider>
          <Toast />
          <ListenerForAuth />
          <Connection />
          <Analyzer />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
