import mongoose from "mongoose";

// Message schema
const GroupMessageSchema = new mongoose.Schema(
  {
    customId: { type: String, required: true }, // this uuid generated by the front end
    chatId: { type: String, required: true },
    senderId: {
      type: String,
      required: false,
    },
    content: { // this is the message content
      type: String,
      required: false,
    },
    status: {
      type: String,
    },
    seenBy: [{ type: String }],
    deliveredTo: [{ type: String }],
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

const GroupMessage =
  mongoose.models.GroupMessage ||
  mongoose.model("GroupMessage", GroupMessageSchema);

export default GroupMessage;
