import mongoose from "mongoose";

// Message schema
const GroupMessageSchema = new mongoose.Schema(
  {
    customId: { type: String, required: true }, // this uuid generated by the front end
    chatId: { type: String, required: true },
    senderInfo: {
      senderId: {
        type: String,
        required: false,
      },
      senderName: {
        type: String,
        required: false,
      },
    },
    content: {
      url: { type: String, required: false },
      format: { type: String, required: false },
      message: { type: String, required: false },
      name: { type: String, required: false },
      public_id: { type: String, required: false },
    },
    status: {
      type: String,
    }, // this status get updated to seen when all groups members see the message, default is sent, it one of the user in group is online then this updated to delivered
    seenBy: [
      {
        userId: { type: String, required: true },
        userName: { type: String, required: true },
        status: { type: String, required: true },
        userDp: {
          type: String,
          required: false,
        },
        // this is individual member message status
      },
    ],
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

const GroupMessage =
  mongoose.models.GroupMessage ||
  mongoose.model("GroupMessage", GroupMessageSchema);

export default GroupMessage;
